# Generated by Django 2.1 on 2018-10-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateTimeField()),
                ('cd', models.CharField(max_length=20)),
                ('fundador', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estadio', models.CharField(max_length=30)),
                ('fecha_construccion', models.DateTimeField()),
                ('direccion', models.CharField(max_length=25)),
                ('propietario', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fanaticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fanatico', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('edad', models.FloatField()),
                ('numero_cel', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo_fanatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=40)),
                ('edad', models.FloatField()),
                ('posicion', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Equipos')),
            ],
        ),
    ]
