# Generated by Django 2.1 on 2018-10-07 04:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_asientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='estadio',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='reportes.Estadios'),
            preserve_default=False,
        ),
    ]
