# Generated by Django 2.1 on 2018-10-07 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_asientos_estadio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientos',
            name='estadio',
            field=models.ForeignKey(default='desconocido', on_delete=django.db.models.deletion.CASCADE, to='reportes.Estadios'),
        ),
    ]
