# Generated by Django 2.1 on 2018-10-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_auto_20181007_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientos',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Estadios'),
        ),
    ]
