# Generated by Django 2.1 on 2018-10-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_remove_asientos_estadio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientos',
            name='categoria',
        ),
    ]
