# Generated by Django 2.1 on 2018-10-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_remove_asientos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='categoria',
            field=models.CharField(default='baja', max_length=15),
        ),
        migrations.AddField(
            model_name='asientos',
            name='estadio',
            field=models.ForeignKey(default='desconocido', on_delete=django.db.models.deletion.CASCADE, to='reportes.Estadios'),
        ),
        migrations.AlterField(
            model_name='asientos',
            name='numero_asiento',
            field=models.FloatField(),
        ),
    ]
