# Generated by Django 2.1 on 2018-10-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_auto_20181007_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento_Palco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('numero_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Asientos')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Palco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_renta', models.IntegerField(default=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palcos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_palco', models.IntegerField()),
                ('categoria', models.CharField(default='club', max_length=15)),
                ('cantidad_asientos', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fanaticos',
            name='palco',
            field=models.CharField(default='sin palco', max_length=10),
        ),
        migrations.AlterField(
            model_name='fanaticos',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='contrato_palco',
            name='nombre_fanatico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Fanaticos'),
        ),
        migrations.AddField(
            model_name='contrato_palco',
            name='numero_palco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Palcos'),
        ),
        migrations.AddField(
            model_name='asiento_palco',
            name='numero_palco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Palcos'),
        ),
    ]
