# Generated by Django 2.1 on 2018-10-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_palcos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palcos',
            name='estado',
            field=models.CharField(default='disponible', max_length=15),
        ),
    ]
