# Generated by Django 2.1 on 2018-10-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_auto_20181007_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_fanatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Fanaticos')),
                ('numero_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Asientos')),
            ],
        ),
    ]
